### PR TITLE
feat(watt): extend icon to support state colors

### PR DESCRIPTION
**Pull request by dzhavat**
### Watt Design System
- Extend icon to support state colors
- Update Storybook to showcase examples

image

### DataHub
- Refactor component to use state property on icon component

## References

- https://github.com/Energinet-DataHub/greenforce-frontend/issues/295

### CODE REVIEW

**Review by frontend-specialisten — DISMISSED** [review]

**Review by frontend-specialisten — APPROVED** [review]

**Comment by MadsBloendAndersen** [comment]
@dzhavat is it on purpose that there is a checkmark inside each state? Shouldn't the icon also reflect the state?

**Comment by dzhavat** [comment]
@MadsBloendAndersen Yes, the checkbox icon is used intentionally to show that we can set any state on an icon. I can also understand your argument that the icon reflects the state (in our case it will be the other way, i.e. the state will reflect the icon because the icon name is required but the state is not. That's a detail). So the `success` icon always shows in "Success" state, etc. Good point. Maybe we should consider it. What do you think @frontend-specialisten

**Comment by frontend-specialisten** [comment]
I think that we properly could have some more sensible default states of some of the icons like succes, warnings etc. However I only think that they should be defaults so you still have the flexibility to overwrite it.

**Comment by dzhavat** [comment]
@MadsBloendAndersen @frontend-specialisten I just opened #326 which adds default state to these four icons (`success`, `danger`, `warning` and `info`) with the option to overwrite it.

**Pull request merged**
