### PR TITLE
feat(ui-watt): paginator style

### PR DESCRIPTION
**Pull request by ManBearTM**
## Description
This PR simply applies some global styling to the mat-paginator component.

## References

- #592

### CODE REVIEW

**Comment by dzhavat** [comment]
praise: looks quite nice 💪 Good job.

question: have you checked whether/how the styling affects the `mat-paginator` components used in the DH app? I'm not sure if other teams have tried styling the paginator in their components, thus causing some styling issues.

**Comment by ManBearTM** [comment]
> question: have you checked whether/how the styling affects the `mat-paginator` components used in the DH app? I'm not sure if other teams have tried styling the paginator in their components, thus causing some styling issues.

I have not, good idea. I will give it a look.

**Comment by ManBearTM** [comment]
pagination
Looks okay 🙂

**Comment by dzhavat** [comment]
Looks nice 🌟 

So it's only a matter of EO bump and `main` merge, and we're good to go :)

**Review by dzhavat — APPROVED** [review]

**Review by dzhavat — APPROVED** [review]

**Pull request merged**
