### PR TITLE
Feature/logo

### PR DESCRIPTION
**Pull request by Klemmensen**
## Description

Adds the Energinet logo above the navigation on the "logged in area of the application"

## References

https://github.com/Energinet-DataHub/energy-origin/issues/397

### CODE REVIEW

**Review by LayZeeDK — CHANGES_REQUESTED** [review]
The spacing in the layout of the logo in the navigation drawer does not look correct, at least not on my machine 🤷‍♂️

**Current implementation**
image

**Figma**
image

**Comment by Klemmensen** [comment]
> The spacing in the layout of the logo in the navigation drawer does not look correct, at least not on my machine 🤷‍♂️
> 
> **Current implementation** image
> 
> **Figma** image

Hi @LayZeeDK Can you try and look again? I'm not sure if something has been partly cached or what has happened. When I look local and on the feature env it seems to be aligned.

image

**Comment by LayZeeDK** [comment]
@Klemmensen 
I see the issue right there in your screenshot
image

**Review by LayZeeDK — APPROVED** [review]
🍰

**Pull request merged**
