### PR TITLE
Change prefix for DataHub project

### PR DESCRIPTION
**Pull request by dzhavat**
## Description

* Change prefix for DataHub project 
* Change NX default base branch

## References

-#

### CODE REVIEW

**Review by LayZeeDK — CHANGES_REQUESTED** [review]
I thought we were using `gf` (Green Force), not `dh` (DataHub) 🤔

We're going to use `ett` (Energy Track and Trace) in Energioprindelse.

**Comment by dzhavat** [comment]
> I though we were using gf (Green Force), not dh (DataHub) 🤔

"Green Force" is the name of the ART. The DataHub app is still called DataHub.

**Comment by LayZeeDK** [comment]
Maybe we shouldn't have a global prefix setting then. Each project will need to have `dh` or `ett` specified.

**Comment by dzhavat** [comment]
Do you mean the `defaultProject` setting?

**Comment by LayZeeDK** [comment]
> Do you mean the defaultProject setting?

Sorry, I thought this was a global `prefix` setting. Nevermind me!

**Review by LayZeeDK — APPROVED** [review]

**Comment by dzhavat** [comment]
> Which npmScope will we use?

I'm not sure what is the difference if we change it. Right now it's `energinet`. The Watt Design System is also imported by `@energinet/watt` which I think is fine. Even if it gets moved to a different repo, the same import still makes sense.

**Review by frontend-specialisten — APPROVED** [review]
Agreed, I think energinet makes sense of npmScope and the different applications should have their own prefix

**Pull request merged**
